// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"yy-shop/internal/biz"
	"yy-shop/internal/conf"
	"yy-shop/internal/data"
	"yy-shop/internal/server"
	"yy-shop/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	encryptService := biz.NewEncryptService()
	accountUseCase := biz.NewAccountUseCase(logger, bootstrap, userRepo, encryptService)
	accountServer := service.NewAccountService(logger, accountUseCase)
	grpcServer := server.NewGRPCServer(confServer, logger, accountServer)
	httpServer := server.NewHTTPServer(confServer, accountServer, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
